// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/app"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/config"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/controllers"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/domain/items"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/services"
	"net/http"
)

// Injectors from wire.go:

func inject(appConfig *config.Config) *app.Application {
	client := _wireClientValue
	oAuthClient := app.ProvideOAuthClient(client, appConfig)
	itemsPersistInterface := items.NewItemPersister()
	itemsServiceInterface := services.NewItemsService(itemsPersistInterface)
	itemControllerInterface := controllers.NewItemController(oAuthClient, itemsServiceInterface)
	application := app.NewApp(appConfig, itemControllerInterface)
	return application
}

var (
	_wireClientValue = http.DefaultClient
)
