// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_users_api/app"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_users_api/conf"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_users_api/controllers"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_users_api/dao/mysql"
	"github.com/chernyshev-alex/bookstore/cmd/bookstore_users_api/services"
	"net/http"
)

// Injectors from wire.go:

func inject(conf2 *conf.Config) app.Application {
	pingController := controllers.ProvidePingController()
	config := mysql.MakeConfig(conf2)
	db := mysql.NewSqlClient(config)
	userDao := mysql.NewUserDao(db)
	userService := services.NewService(userDao)
	client := _wireClientValue
	oAuthClient := app.NewOAuthClient(client, conf2)
	userController := controllers.ProvideUserController(userService, oAuthClient)
	application := app.ProvideApp(conf2, pingController, userController)
	return application
}

var (
	_wireClientValue = http.DefaultClient
)
