// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/chernyshev-alex/bookstore-oauth-go/oauth"
	"github.com/chernyshev-alex/bookstore_users-api/app"
	"github.com/chernyshev-alex/bookstore_users-api/controllers/ping"
	users2 "github.com/chernyshev-alex/bookstore_users-api/controllers/users"
	"github.com/chernyshev-alex/bookstore_users-api/datasources/mysql/users_db"
	"github.com/chernyshev-alex/bookstore_users-api/domain/users"
	"github.com/chernyshev-alex/bookstore_users-api/services"
	"github.com/go-sql-driver/mysql"
	"net/http"
)

// Injectors from wire.go:

func inject(mysqlConf mysql.Config) app.Application {
	pingController := ping.ProvidePingController()
	db := users_db.ProvideSqlClient(mysqlConf)
	userDAO := users.ProvideUserDao(db)
	usersService := services.ProvideUserService(userDAO)
	client := _wireClientValue
	oAuthClient := oauth.ProvideOAuthClient(client)
	userController := users2.ProvideUserController(usersService, oAuthClient)
	application := app.ProvideApp(pingController, userController)
	return application
}

var (
	_wireClientValue = http.DefaultClient
)
