// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	items "github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/domain/items"
	mock "github.com/stretchr/testify/mock"

	queries "github.com/chernyshev-alex/bookstore/cmd/bookstore_items-api/domain/queries"

	rest_errors "github.com/chernyshev-alex/bookstore/pkg/bookstore_utils_go/rest_errors"
)

// ItemsPersistInterface is an autogenerated mock type for the ItemsPersistInterface type
type ItemsPersistInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *ItemsPersistInterface) Get(_a0 items.Item) (*items.Item, rest_errors.RestErr) {
	ret := _m.Called(_a0)

	var r0 *items.Item
	if rf, ok := ret.Get(0).(func(items.Item) *items.Item); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*items.Item)
		}
	}

	var r1 rest_errors.RestErr
	if rf, ok := ret.Get(1).(func(items.Item) rest_errors.RestErr); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(rest_errors.RestErr)
		}
	}

	return r0, r1
}

// Save provides a mock function with given fields: it
func (_m *ItemsPersistInterface) Save(it *items.Item) rest_errors.RestErr {
	ret := _m.Called(it)

	var r0 rest_errors.RestErr
	if rf, ok := ret.Get(0).(func(*items.Item) rest_errors.RestErr); ok {
		r0 = rf(it)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest_errors.RestErr)
		}
	}

	return r0
}

// Search provides a mock function with given fields: q
func (_m *ItemsPersistInterface) Search(q queries.EsQuery) ([]items.Item, rest_errors.RestErr) {
	ret := _m.Called(q)

	var r0 []items.Item
	if rf, ok := ret.Get(0).(func(queries.EsQuery) []items.Item); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]items.Item)
		}
	}

	var r1 rest_errors.RestErr
	if rf, ok := ret.Get(1).(func(queries.EsQuery) rest_errors.RestErr); ok {
		r1 = rf(q)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(rest_errors.RestErr)
		}
	}

	return r0, r1
}
