// Code generated by sqlc. DO NOT EDIT.

package user_dao

import (
	"database/sql"
	"time"
)

type User struct {
	ID          int32          `json:"id"`
	FirstName   sql.NullString `json:"firstName"`
	LastName    sql.NullString `json:"lastName"`
	Email       string         `json:"email"`
	DateCreated time.Time      `json:"dateCreated"`
	Status      sql.NullString `json:"status"`
	Password    sql.NullString `json:"password"`
}
